# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8486845a2df8e1cae887525d9a4344b86744dca523217affee4ff4962e5f232663b9bf79f363da4e9e1f8e262a98f50d64397a03f0726e7f9706f49e8932630d

test:
  secret_key_base: 867368004135b7e88c098e325e1f0854f946d6152c1af2c4cdd79cae4640a59b966445fc35b4b96e56054e52aa8b4e313fae4fffbe4bbc26f38eaa8d23ac6331

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
